### PR TITLE
Add jvillarr to completed.lab

### PR DESCRIPTION
**Pull request by jvillarr**

### CODE REVIEW

**Comment by vvaldez** [comment]
Can you try again? There was a merge conflict since someone else beat you to this change (this is intentional, see the merge section in the lab).

**Comment by jvillarr** [comment]
I am still getting the same error


[jvillarr@jvillarr github]$git clone git@github.com:vvaldez/practice-labs.git
[jvillarr@jvillarr github]$cd practice-labs
[jvillarr@jvillarr practice-labs{master}]$git remote add upstream git@github.com:cloud-practice/practice-labs.git
[jvillarr@jvillarr practice-labs{master}]$git branch practice-labs-jv
[jvillarr@jvillarr practice-labs{master}]$git checkout practice-labs-jv
[jvillarr@jvillarr practice-labs{practice-labs-jv}]$echo "jvillarr" >> completed.lab
[jvillarr@jvillarr practice-labs{practice-labs-jv}]$ git diff
diff --git a/completed.lab b/completed.lab
index 4f136c5..8be5cec 100644
--- a/completed.lab
+++ b/completed.lab
@@ -14,4 +14,4 @@ gutseb
 mrgiles
 dantrainor
 ShaddGallegos
- 
+jvillarr 
[jvillarr@jvillarr practice-labs{practice-labs-jv}]$ git add completed.lab
[jvillarr@jvillarr practice-labs{practice-labs-jv}]$ git commit
[practice-labs-jv 02ee73d] 	modified:   completed.lab
 1 files changed, 1 insertions(+), 1 deletions(-)
[jvillarr@jvillarr practice-labs{practice-labs-jv}]$ git checkout master
Switched to branch 'master'
[jvillarr@jvillarr practice-labs{master}]$ git fetch upstream
remote: Counting objects: 137, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 137 (delta 31), reused 4 (delta 4), pack-reused 103
Receiving objects: 100% (137/137), 32.13 KiB, done.
Resolving deltas: 100% (64/64), done.
From github.com:cloud-practice/practice-labs
 * [new branch]      master     -> upstream/master
[jvillarr@jvillarr practice-labs{master}]$ git merge upstream/master
Updating c76ffd5..4cd8685
Fast-forward
 README.md      |    3 +-
 completed.lab  |   28 ++++++-
 dcritch.adoc   |   10 ---
 lab.adoc       |  244 +++++++++++++++++++++++++++++++++++++++++++++++--------
 4 files changed, 236 insertions(+), 49 deletions(-)
 delete mode 100644 DanT_Stuff.txt
 delete mode 100644 dcritch.adoc
[jvillarr@jvillarr practice-labs{master}]$ git push --set-upstream origin practice-labs
ERROR: Permission to vvaldez/practice-labs.git denied to jvillarr.
fatal: The remote end hung up unexpectedly
[jvillarr@jvillarr practice-labs{master}]$ git push --set-upstream origin practice-lab-jv
ERROR: Permission to vvaldez/practice-labs.git denied to jvillarr.
fatal: The remote end hung up unexpectedly
[jvillarr@jvillarr practice-labs{master}]$ 


James Villarreal RHCE
Red Hat Consulting
Cell: 512-351-6842
jvillarr@redhat.com
http://www.redhat.com

----- Original Message -----

**Comment by vvaldez** [comment]
You will want to work out of your fork instead of trying to push directly to my fork. Your git clone should be
git clone git@github.com:jvillarr/practice-labs.git

You can try deleting your local clone and start over in the lab steps, make sure to fork and clone your own fork

**Comment by vvaldez** [comment]
Do you still need this? Please re-open and try again when you are ready.

**Pull request closed without merging**
