### PR TITLE
Adding account chrisslamar to the list of completed

### PR DESCRIPTION
**Pull request by chrisslamar**

### CODE REVIEW

**Comment by vvaldez** [comment]
Can you try to resolve the merge conflict? Someone beat you to a PR>

**Comment by chrisslamar** [comment]
Vinny,
  I've tried about six times now to get a merge conflict, and cannot get the local repo to show that I have a merge conflict, and have to use mergetool.  I've followed the directions, and it just won't break (first time I've ever wished for a merge conflict).  Please let me know if there's anything else I should try.  Sorry for the delay and confusion.

--Chris

Chris Slamar
(224) 412-2072
cslamar@redhat.com

----- Original Message -----

**Comment by vvaldez** [comment]
No problem, sorry for the delayed reply. You're good now right?

Chris Slamar wrote:
> Vinny,
> I've tried about six times now to get a merge conflict, and cannot get 
> the local repo to show that I have a merge conflict, and have to use 
> mergetool. I've followed the directions, and it just won't break 
> (first time I've ever wished for a merge conflict). Please let me know 
> if there's anything else I should try. Sorry for the delay and confusion.
>
> --Chris
>
> Chris Slamar
> (224) 412-2072
> cslamar@redhat.com
>
> ----- Original Message -----
> From: "Vinny Valdez" <notifications@github.com>
> To: "cloud-practice/practice-labs" <practice-labs@noreply.github.com>
> Cc: "Chris Slamar" <cslamar@redhat.com>
> Sent: Sunday, June 7, 2015 12:15:21 AM
> Subject: Re: [practice-labs] Adding account chrisslamar to the list of 
> completed (#100)
>
> Can you try to resolve the merge conflict? Someone beat you to a PR>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/cloud-practice/practice-labs/pull/100#issuecomment-109694492
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cloud-practice/practice-labs/pull/100#issuecomment-109775532>.
>

-- 
Vinny Valdez, RHCA, RHCSS, RHCVA (110-119-187)
Principal OpenStack Architect
Cloud Practice
+1 (512) 718-5572
My free/busy times: 
https://www.google.com/calendar/embed?src=vvaldez%40redhat.com&ctz=America/Chicago

**Comment by chrisslamar** [comment]
Yep, I'm good

--Chris Slamar
(224) 412-2072

**Pull request closed without merging**
