### PR TITLE
adding ealcaniz

### PR DESCRIPTION
**Pull request by ealcaniz**

### CODE REVIEW

**Comment by vvaldez** [comment]
Can you fix this merge conflict? Someone beat you to their pull request. See the merge conflict section in the lab.

**Comment by ealcaniz** [comment]
I already did it, it doesnt seems update completed.lab in master

Thanks. 
Edu Alcaniz 
Senior Consultant Platform 
Red Hat 

----- Original Message -----

**Comment by vvaldez** [comment]
Try again, your completed.lab should have kyle at the bottom.

https://github.com/cloud-practice/practice-labs/blob/master/completed.lab

Edu Alcañiz wrote:
> I already did it, it doesnt seems update completed.lab in master
>
> Thanks.
> Edu Alcaniz
> Senior Consultant Platform
> Red Hat
>
> ----- Original Message -----
> From: "Vinny Valdez" <notifications@github.com>
> To: "cloud-practice/practice-labs" <practice-labs@noreply.github.com>
> Cc: "Edu Alcañiz" <ealcaniz@redhat.com>
> Sent: Thursday, 4 June, 2015 11:09:47 AM
> Subject: Re: [practice-labs] adding ealcaniz (#93)
>
> Can you fix this merge conflict? Someone beat you to their pull 
> request. See the merge conflict section in the lab.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/cloud-practice/practice-labs/pull/93#issuecomment-108796214
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cloud-practice/practice-labs/pull/93#issuecomment-108796761>.
>

-- 
Vinny Valdez, RHCA, RHCSS, RHCVA (110-119-187)
Principal OpenStack Architect
Cloud Practice
+1 (512) 718-5572
My free/busy times: 
https://www.google.com/calendar/embed?src=vvaldez%40redhat.com&ctz=America/Chicago

**Comment by ealcaniz** [comment]
yes I did it.

[ealcaniz@ealcaniz practice-labs{ealcaniz}]$ git commit -am "adding ealcaniz"
[ealcaniz f9a779c] adding ealcaniz
 1 file changed, 1 insertion(+), 1 deletion(-)
[ealcaniz@ealcaniz practice-labs{ealcaniz}]$ git checkout master 
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
[ealcaniz@ealcaniz practice-labs{master}]$ git fetch upstream 
[ealcaniz@ealcaniz practice-labs{master}]$ git merge upstream/master 
Already up-to-date.
[ealcaniz@ealcaniz practice-labs{master}]$ cat completed.lab | grep ealcaniz
[ealcaniz@ealcaniz practice-labs{master}]$ 

it seems it doesn't merge

[ealcaniz@ealcaniz practice-labs{master}]$ git push --set-upstream origin ealcaniz
To git@github.com:ealcaniz/practice-labs.git
 ! [rejected]        ealcaniz -> ealcaniz (non-fast-forward)
error: failed to push some refs to 'git@github.com:ealcaniz/practice-labs.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[ealcaniz@ealcaniz practice-labs{master}]$ 


I remove everything and I did again, same issue

**Comment by ealcaniz** [comment]
seems sort out

[ealcaniz@ealcaniz practice-labs{master}]$ git push --force origin ealcaniz
Everything up-to-date
[ealcaniz@ealcaniz practice-labs{master}]$ git merge origin/ealcaniz 
Updating 1346bb8..f9a779c
Fast-forward
 completed.lab | 1 +
 1 file changed, 1 insertion(+)
[ealcaniz@ealcaniz practice-labs{master}]$ git push
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:ealcaniz/practice-labs.git
   1346bb8..f9a779c  master -> master
[ealcaniz@ealcaniz practice-labs{master}]$ cat completed.lab | grep ealcaniz
ealcaniz 
[ealcaniz@ealcaniz practice-labs{master}]$

**Pull request merged**
